-- MySQL Script generated by MySQL Workbench
-- Sun Sep 12 16:30:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema computer-combat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema computer-combat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `computer-combat` DEFAULT CHARACTER SET utf8 ;
USE `computer-combat` ;

-- -----------------------------------------------------
-- Table `computer-combat`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer-combat`.`Profile` (
  `idProfile` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(20) NOT NULL,
  `email` TEXT(40) NOT NULL,
  PRIMARY KEY (`idProfile`),
  UNIQUE INDEX `idProfile_UNIQUE` (`idProfile` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer-combat`.`Deck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer-combat`.`Deck` (
  `idDeck` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idDeck`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer-combat`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer-combat`.`Card` (
  `idCard` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `maxHealth` INT NULL,
  `maxDefense` INT NULL,
  `maxAttack` INT NULL,
  `runRequirements` INT NULL,
  `level` INT NULL,
  `textureName` INT NULL,
  PRIMARY KEY (`idCard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer-combat`.`Components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer-combat`.`Components` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `textureName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer-combat`.`Pack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer-combat`.`Pack` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `textureName` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
