-- MySQL Script generated by MySQL Workbench
-- Fri Sep 17 00:33:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema computer_combat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema computer_combat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `computer_combat` DEFAULT CHARACTER SET utf8 ;
USE `computer_combat` ;

-- -----------------------------------------------------
-- Table `computer_combat`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`profile` (
  `idProfile` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(20) NOT NULL,
  `email` TEXT(40) NOT NULL,
  PRIMARY KEY (`idProfile`),
  UNIQUE INDEX `idProfile_UNIQUE` (`idProfile` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`deck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`deck` (
  `idDeck` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Profile_idProfile` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDeck`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Deck_Profile_idx` (`Profile_idProfile` ASC) VISIBLE,
  CONSTRAINT `fk_Deck_Profile`
    FOREIGN KEY (`Profile_idProfile`)
    REFERENCES `computer_combat`.`profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`collection` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `textureName` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`ability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`ability` (
  `idAbility` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `textureName` VARCHAR(45) NULL,
  PRIMARY KEY (`idAbility`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`card` (
  `idCard` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `maxHealth` INT NOT NULL,
  `maxDefense` INT NOT NULL,
  `maxAttack` INT NOT NULL,
  `runRequirements` INT NOT NULL,
  `level` INT NOT NULL,
  `textureName` INT NOT NULL,
  `Pack_id` INT NOT NULL,
  `Ability_idAbility` INT NOT NULL,
  PRIMARY KEY (`idCard`, `Pack_id`, `Ability_idAbility`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Card_Pack1_idx` (`Pack_id` ASC) VISIBLE,
  INDEX `fk_Card_Ability1_idx` (`Ability_idAbility` ASC) VISIBLE,
  CONSTRAINT `fk_Card_Pack1`
    FOREIGN KEY (`Pack_id`)
    REFERENCES `computer_combat`.`collection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Ability1`
    FOREIGN KEY (`Ability_idAbility`)
    REFERENCES `computer_combat`.`ability` (`idAbility`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`components` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `textureName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`run_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`run_requirements` (
  `Card_idCard` INT NOT NULL,
  `Card_Pack_id` INT NOT NULL,
  `Components_id` INT NOT NULL,
  PRIMARY KEY (`Card_idCard`, `Card_Pack_id`, `Components_id`),
  INDEX `fk_Card_has_Components_Components1_idx` (`Components_id` ASC) VISIBLE,
  INDEX `fk_Card_has_Components_Card1_idx` (`Card_idCard` ASC, `Card_Pack_id` ASC) VISIBLE,
  CONSTRAINT `fk_Card_has_Components_Card1`
    FOREIGN KEY (`Card_idCard` , `Card_Pack_id`)
    REFERENCES `computer_combat`.`card` (`idCard` , `Pack_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_has_Components_Components1`
    FOREIGN KEY (`Components_id`)
    REFERENCES `computer_combat`.`components` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`deck_has_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`deck_has_card` (
  `Deck_idDeck` INT NOT NULL,
  `Card_idCard` INT NOT NULL,
  `Card_Pack_id` INT NOT NULL,
  PRIMARY KEY (`Deck_idDeck`, `Card_idCard`, `Card_Pack_id`),
  INDEX `fk_Deck_has_Card_Card1_idx` (`Card_idCard` ASC, `Card_Pack_id` ASC) VISIBLE,
  INDEX `fk_Deck_has_Card_Deck1_idx` (`Deck_idDeck` ASC) VISIBLE,
  CONSTRAINT `fk_Deck_has_Card_Deck1`
    FOREIGN KEY (`Deck_idDeck`)
    REFERENCES `computer_combat`.`deck` (`idDeck`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deck_has_Card_Card1`
    FOREIGN KEY (`Card_idCard` , `Card_Pack_id`)
    REFERENCES `computer_combat`.`card` (`idCard` , `Pack_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`profile_owns_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`profile_owns_card` (
  `Profile_idProfile` VARCHAR(45) NOT NULL,
  `Card_idCard` INT NOT NULL,
  `Card_Pack_id` INT NOT NULL,
  PRIMARY KEY (`Profile_idProfile`, `Card_idCard`, `Card_Pack_id`),
  INDEX `fk_Profile_has_Card_Card1_idx` (`Card_idCard` ASC, `Card_Pack_id` ASC) VISIBLE,
  INDEX `fk_Profile_has_Card_Profile1_idx` (`Profile_idProfile` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_has_Card_Profile1`
    FOREIGN KEY (`Profile_idProfile`)
    REFERENCES `computer_combat`.`profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_has_Card_Card1`
    FOREIGN KEY (`Card_idCard` , `Card_Pack_id`)
    REFERENCES `computer_combat`.`card` (`idCard` , `Pack_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'jan' IDENTIFIED BY 'megladon75';

GRANT ALL ON `computer_combat`.* TO 'jan';
GRANT SELECT ON TABLE `computer_combat`.* TO 'jan';
GRANT SELECT, INSERT, TRIGGER ON TABLE `computer_combat`.* TO 'jan';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `computer_combat`.* TO 'jan';
GRANT EXECUTE ON ROUTINE `computer_combat`.* TO 'jan';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
