-- MySQL Script generated by MySQL Workbench
-- Tue Nov 16 14:04:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema computer_combat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema computer_combat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `computer_combat` DEFAULT CHARACTER SET utf8 ;
USE `computer_combat` ;

-- -----------------------------------------------------
-- Table `computer_combat`.`ability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`ability` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `code` TEXT NOT NULL,
  `textureName` VARCHAR(45) NULL DEFAULT NULL,
  `collection_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`collection` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `textureName` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`card` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `maxHealth` INT NOT NULL,
  `maxDefense` INT NOT NULL,
  `maxAttack` INT NOT NULL,
  `runRequirements` INT NOT NULL,
  `level` INT NOT NULL,
  `textureName` VARCHAR(45) NOT NULL,
  `collection_id` INT NOT NULL,
  `ability_id` INT NOT NULL,
  PRIMARY KEY (`id`, `collection_id`, `ability_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Card_Pack1_idx` (`collection_id` ASC) VISIBLE,
  INDEX `fk_Card_Ability1_idx` (`ability_id` ASC) VISIBLE,
  CONSTRAINT `fk_Card_Ability1`
    FOREIGN KEY (`ability_id`)
    REFERENCES `computer_combat`.`ability` (`id`),
  CONSTRAINT `fk_Card_Pack1`
    FOREIGN KEY (`collection_id`)
    REFERENCES `computer_combat`.`collection` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`components` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `textureName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`profile` (
  `uid` VARCHAR(45) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `email` TINYTEXT NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `idProfile_UNIQUE` (`uid` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`deck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`deck` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `profile_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Deck_Profile_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_Deck_Profile`
    FOREIGN KEY (`profile_id`)
    REFERENCES `computer_combat`.`profile` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`deck_has_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`deck_has_card` (
  `deck_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  `amount` INT NULL DEFAULT NULL,
  UNIQUE INDEX `deck_id_UNIQUE` (`deck_id` ASC) VISIBLE,
  UNIQUE INDEX `card_id_UNIQUE` (`card_id` ASC) VISIBLE,
  INDEX `fk_Deck_has_Card_Deck1_idx` (`deck_id` ASC) VISIBLE,
  INDEX `fk_Deck_has_Card_Card1_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `fk_Deck_has_Card_Card1`
    FOREIGN KEY (`card_id`)
    REFERENCES `computer_combat`.`card` (`id`),
  CONSTRAINT `fk_Deck_has_Card_Deck1`
    FOREIGN KEY (`deck_id`)
    REFERENCES `computer_combat`.`deck` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`profile_owns_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`profile_owns_card` (
  `profile_id` VARCHAR(45) NOT NULL,
  `card_id` INT NOT NULL,
  INDEX `fk_Profile_has_Card_Profile1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_Profile_has_Card_Card1_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_has_Card_Card1`
    FOREIGN KEY (`card_id`)
    REFERENCES `computer_combat`.`card` (`id`),
  CONSTRAINT `fk_Profile_has_Card_Profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `computer_combat`.`profile` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`run_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`run_requirements` (
  `card_id` INT NOT NULL,
  `collection_id` INT NOT NULL,
  `component_id` INT NOT NULL,
  PRIMARY KEY (`card_id`, `collection_id`, `component_id`),
  INDEX `fk_Card_has_Components_Components1_idx` (`component_id` ASC) VISIBLE,
  INDEX `fk_Card_has_Components_Card1_idx` (`card_id` ASC, `collection_id` ASC) VISIBLE,
  CONSTRAINT `fk_Card_has_Components_Card1`
    FOREIGN KEY (`card_id` , `collection_id`)
    REFERENCES `computer_combat`.`card` (`id` , `collection_id`),
  CONSTRAINT `fk_Card_has_Components_Components1`
    FOREIGN KEY (`component_id`)
    REFERENCES `computer_combat`.`components` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`match` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player1_uid` VARCHAR(45) NOT NULL,
  `player2_uid` VARCHAR(45) NOT NULL,
  `deck1_id` INT NOT NULL,
  `deck2_id` INT NOT NULL,
  `winner` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Match_profile1_idx` (`player1_uid` ASC) VISIBLE,
  INDEX `fk_Match_profile2_idx` (`player2_uid` ASC) VISIBLE,
  INDEX `fk_Match_deck1_idx` (`deck1_id` ASC) VISIBLE,
  INDEX `fk_Match_deck2_idx` (`deck2_id` ASC) VISIBLE,
  CONSTRAINT `fk_Match_profile1`
    FOREIGN KEY (`player1_uid`)
    REFERENCES `computer_combat`.`profile` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_profile2`
    FOREIGN KEY (`player2_uid`)
    REFERENCES `computer_combat`.`profile` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_deck1`
    FOREIGN KEY (`deck1_id`)
    REFERENCES `computer_combat`.`deck` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_deck2`
    FOREIGN KEY (`deck2_id`)
    REFERENCES `computer_combat`.`deck` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`match_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`match_state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `match_id` INT UNSIGNED NOT NULL,
  `match_state_number` INT NOT NULL,
  `data` JSON NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MatchState_Match1_idx` (`match_id` ASC) VISIBLE,
  CONSTRAINT `fk_MatchState_Match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `computer_combat`.`match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`move_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`move_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computer_combat`.`move`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`move` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` JSON NOT NULL,
  `match_id` INT UNSIGNED NOT NULL,
  `move_results_id` INT NOT NULL,
  `move_number` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_move_match1_idx` (`match_id` ASC) VISIBLE,
  INDEX `fk_move_move_results1_idx` (`move_results_id` ASC) VISIBLE,
  CONSTRAINT `fk_move_match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `computer_combat`.`match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_move_move_results1`
    FOREIGN KEY (`move_results_id`)
    REFERENCES `computer_combat`.`move_results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
