-- MySQL Script generated by MySQL Workbench
-- Fri Mar  4 13:55:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema computer_combat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema computer_combat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `computer_combat` DEFAULT CHARACTER SET utf8 ;
USE `computer_combat` ;

-- -----------------------------------------------------
-- Table `computer_combat`.`ability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`ability` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `code` TEXT NOT NULL,
  `textureName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`card` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `maxHealth` INT NOT NULL,
  `maxDefense` INT NOT NULL,
  `maxAttack` INT NOT NULL,
  `runRequirements` INT NOT NULL,
  `level` INT NOT NULL,
  `textureName` VARCHAR(45) NOT NULL,
  `collection_id` INT UNSIGNED NOT NULL,
  `ability_id` INT NOT NULL,
  `rarity` INT UNSIGNED NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`, `ability_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Card_Pack1_idx` (`collection_id` ASC) VISIBLE,
  INDEX `fk_Card_Ability1_idx` (`ability_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`collection` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `textureName` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT NOT NULL DEFAULT '50',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`components` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `textureName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`profile` (
  `uid` VARCHAR(45) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `email` TINYTEXT NOT NULL,
  `packets` INT(10) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `idProfile_UNIQUE` (`uid` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`deck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`deck` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `profile_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Deck_Profile_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_Deck_Profile`
    FOREIGN KEY (`profile_id`)
    REFERENCES `computer_combat`.`profile` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`deck_has_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`deck_has_card` (
  `deck_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  `amount` INT NULL DEFAULT NULL,
  INDEX `fk_Deck_has_Card_Deck1_idx` (`deck_id` ASC) VISIBLE,
  INDEX `fk_Deck_has_Card_Card1_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `fk_Deck_has_Card_Card1`
    FOREIGN KEY (`card_id`)
    REFERENCES `computer_combat`.`card` (`id`),
  CONSTRAINT `fk_Deck_has_Card_Deck1`
    FOREIGN KEY (`deck_id`)
    REFERENCES `computer_combat`.`deck` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`match` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player1_uid` VARCHAR(45) NOT NULL,
  `player2_uid` VARCHAR(45) NOT NULL,
  `deck1_id` INT NOT NULL,
  `deck2_id` INT NOT NULL,
  `winner` TINYINT NULL DEFAULT NULL,
  `starttime` DATETIME NOT NULL,
  `endtime` DATETIME NOT NULL,
  `packets_player1` INT UNSIGNED NOT NULL DEFAULT '0',
  `packets_player2` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Match_profile1_idx` (`player1_uid` ASC) VISIBLE,
  INDEX `fk_Match_profile2_idx` (`player2_uid` ASC) VISIBLE,
  INDEX `fk_Match_deck1_idx` (`deck1_id` ASC) VISIBLE,
  INDEX `fk_Match_deck2_idx` (`deck2_id` ASC) VISIBLE,
  CONSTRAINT `fk_Match_deck1`
    FOREIGN KEY (`deck1_id`)
    REFERENCES `computer_combat`.`deck` (`id`),
  CONSTRAINT `fk_Match_deck2`
    FOREIGN KEY (`deck2_id`)
    REFERENCES `computer_combat`.`deck` (`id`),
  CONSTRAINT `fk_Match_profile1`
    FOREIGN KEY (`player1_uid`)
    REFERENCES `computer_combat`.`profile` (`uid`),
  CONSTRAINT `fk_Match_profile2`
    FOREIGN KEY (`player2_uid`)
    REFERENCES `computer_combat`.`profile` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`match_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`match_state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `match_id` INT UNSIGNED NOT NULL,
  `match_state_number` INT NOT NULL,
  `data` JSON NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MatchState_Match1_idx` (`match_id` ASC) VISIBLE,
  CONSTRAINT `fk_MatchState_Match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `computer_combat`.`match` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`move_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`move_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 207
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`move`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`move` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` JSON NOT NULL,
  `match_id` INT UNSIGNED NOT NULL,
  `move_results_id` INT NOT NULL,
  `move_number` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_move_match1_idx` (`match_id` ASC) VISIBLE,
  INDEX `fk_move_move_results1_idx` (`move_results_id` ASC) VISIBLE,
  CONSTRAINT `fk_move_match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `computer_combat`.`match` (`id`),
  CONSTRAINT `fk_move_move_results1`
    FOREIGN KEY (`move_results_id`)
    REFERENCES `computer_combat`.`move_results` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`player` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deck_id` INT NOT NULL,
  `bot` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`profile_owns_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`profile_owns_card` (
  `profile_id` VARCHAR(45) NOT NULL,
  `card_id` INT NOT NULL,
  `amount` INT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`profile_id`, `card_id`),
  INDEX `fk_Profile_has_Card_Profile1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_Profile_has_Card_Card1_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_has_Card_Card1`
    FOREIGN KEY (`card_id`)
    REFERENCES `computer_combat`.`card` (`id`),
  CONSTRAINT `fk_Profile_has_Card_Profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `computer_combat`.`profile` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `computer_combat`.`run_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`run_requirements` (
  `card_id` INT NOT NULL,
  `component_id` INT NOT NULL,
  PRIMARY KEY (`card_id`, `component_id`),
  INDEX `fk_Card_has_Components_Components1_idx` (`component_id` ASC) VISIBLE,
  INDEX `fk_Card_has_Components_Card1_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `fk_Card_has_Components_Card1`
    FOREIGN KEY (`card_id`)
    REFERENCES `computer_combat`.`card` (`id`),
  CONSTRAINT `fk_Card_has_Components_Components1`
    FOREIGN KEY (`component_id`)
    REFERENCES `computer_combat`.`components` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `computer_combat` ;

-- -----------------------------------------------------
-- Placeholder table for view `computer_combat`.`card_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`card_info` (`card_id` INT, `name` INT, `maxAttack` INT, `maxHealth` INT, `maxDefense` INT, `runRequirements` INT, `level` INT, `textureName` INT, `rarity` INT, `ability_id` INT, `description` INT, `code` INT, `ability_name` INT, `ability_textureName` INT, `component_id` INT, `collection_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `computer_combat`.`card_wins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`card_wins` (`match_id` INT, `deck_id` INT, `card_id` INT, `did_win` INT);

-- -----------------------------------------------------
-- Placeholder table for view `computer_combat`.`deck_wins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computer_combat`.`deck_wins` (`match_id` INT, `deck_id` INT, `did_win` INT);

-- -----------------------------------------------------
-- View `computer_combat`.`card_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `computer_combat`.`card_info`;
USE `computer_combat`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`admin`@`%` SQL SECURITY DEFINER VIEW `computer_combat`.`card_info` AS select `computer_combat`.`card`.`id` AS `card_id`,`computer_combat`.`card`.`name` AS `name`,`computer_combat`.`card`.`maxAttack` AS `maxAttack`,`computer_combat`.`card`.`maxHealth` AS `maxHealth`,`computer_combat`.`card`.`maxDefense` AS `maxDefense`,`computer_combat`.`card`.`runRequirements` AS `runRequirements`,`computer_combat`.`card`.`level` AS `level`,`computer_combat`.`card`.`textureName` AS `textureName`,`computer_combat`.`card`.`rarity` AS `rarity`,`computer_combat`.`ability`.`id` AS `ability_id`,`computer_combat`.`ability`.`description` AS `description`,`computer_combat`.`ability`.`code` AS `code`,`computer_combat`.`ability`.`name` AS `ability_name`,`computer_combat`.`ability`.`textureName` AS `ability_textureName`,`computer_combat`.`components`.`id` AS `component_id`,`computer_combat`.`collection`.`id` AS `collection_id` from ((((`computer_combat`.`card` join `computer_combat`.`ability` on((`computer_combat`.`card`.`ability_id` = `computer_combat`.`ability`.`id`))) join `computer_combat`.`run_requirements` on((`computer_combat`.`card`.`id` = `computer_combat`.`run_requirements`.`card_id`))) join `computer_combat`.`components` on((`computer_combat`.`components`.`id` = `computer_combat`.`run_requirements`.`component_id`))) join `computer_combat`.`collection` on((`computer_combat`.`card`.`collection_id` = `computer_combat`.`collection`.`id`)));

-- -----------------------------------------------------
-- View `computer_combat`.`card_wins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `computer_combat`.`card_wins`;
USE `computer_combat`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`admin`@`%` SQL SECURITY DEFINER VIEW `computer_combat`.`card_wins` AS select `computer_combat`.`deck_wins`.`match_id` AS `match_id`,`computer_combat`.`deck_wins`.`deck_id` AS `deck_id`,`computer_combat`.`deck_has_card`.`card_id` AS `card_id`,`computer_combat`.`deck_wins`.`did_win` AS `did_win` from (`computer_combat`.`deck_wins` join `computer_combat`.`deck_has_card` on((`computer_combat`.`deck_wins`.`deck_id` = `computer_combat`.`deck_has_card`.`deck_id`)));

-- -----------------------------------------------------
-- View `computer_combat`.`deck_wins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `computer_combat`.`deck_wins`;
USE `computer_combat`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`admin`@`%` SQL SECURITY DEFINER VIEW `computer_combat`.`deck_wins` AS select `computer_combat`.`match`.`id` AS `match_id`,`computer_combat`.`deck`.`id` AS `deck_id`,if((((`computer_combat`.`match`.`deck1_id` = `computer_combat`.`deck`.`id`) and (`computer_combat`.`match`.`winner` = 0)) or ((`computer_combat`.`match`.`deck2_id` = `computer_combat`.`deck`.`id`) and (`computer_combat`.`match`.`winner` = 1))),1,0) AS `did_win` from (`computer_combat`.`match` join `computer_combat`.`deck` on(((`computer_combat`.`match`.`deck1_id` = `computer_combat`.`deck`.`id`) or (`computer_combat`.`match`.`deck2_id` = `computer_combat`.`deck`.`id`))));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Add Users
-- -----------------------------------------------------

CREATE USER 'client'@'%' IDENTIFIED BY 'computercombat2021';
GRANT DELETE ON computer_combat.* TO 'client'@'%';
GRANT EXECUTE ON computer_combat.* TO 'client'@'%';
GRANT INSERT ON computer_combat.* TO 'client'@'%';
GRANT SELECT ON computer_combat.* TO 'client'@'%';
GRANT UPDATE ON computer_combat.* TO 'client'@'%';